dist: trusty
env:
  global:
    - MOZ_HEADLESS=1
addons:
  - chrome: stable
  - firefox: latest
language: node_js
node_js:
  - 8
script: npx cross-env BABEL_ENV=test karma start -no-watch --no-progress --single-run